### PR TITLE
refactored the resource docs. also added a new helper that builds code tabs out of a directory on disk.

### PR DESCRIPTION
**Pull request by markbates**

### CODE REVIEW

**Comment by markbates** [comment]
Are you seeing that happen? Any specific place?

**Comment by stanislas-m** [comment]
```
ERRO[2018-10-06T18:39:24+02:00] docs/resources/_example/standard/templates/widgets/show.html: line 6: widgetsPath: unknown identifier duration=6.186841ms human_size="0 B" method=GET params="{\"lang\":[\"en\"],\"name\":[\"resources/_example/standard/templates/widgets/show/\"]}" path=/en/docs/resources/_example/standard/templates/widgets/show/ render="368.942µs" request_id=nqyCTlbmmU-oNblZnaIMI size=0 status=0
could not index /en/docs/resources/_example/standard/templates/widgets/show
```

**Comment by stanislas-m** [comment]
Looks like the indexer is trying to index more than it should. :)

**Comment by markbates** [comment]
@stanislas-m indexer fixed, but my examples seem to be rendering fine.

**Comment by markbates** [comment]
image

**Pull request merged**
